CREATE DATABASE IF NOT EXISTS personas_db;
USE personas_db;
CREATE TABLE personas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  Apellidos VARCHAR(255) NOT NULL,
  Nombres VARCHAR(255) NOT NULL,
  dni INT PRIMARY KEY
);
